// Generated by CoffeeScript 1.4.0
var admin, blog, demo, file, index, login, mail, signup, socket, user, xml;

index = require('./controllers/index');

signup = require('./controllers/signup');

login = require('./controllers/login');

user = require('./controllers/user');

file = require('./controllers/file');

mail = require('./controllers/mail');

socket = require('./controllers/socket.io');

blog = require('./controllers/blog');

demo = require('./controllers/demo');

xml = require('./controllers/xmlTest');

admin = require('./controllers/admin');

module.exports = function(app) {
  app.all('*', index.auth);
  app.get('/', index.get);
  app.get('/signup', signup.get);
  app.post('/signup', signup.validator, signup.post);
  app.get('/finish', signup.finish);
  app.get('/login', login.get);
  app.post('/login', login.validator, login.post);
  app.get('/logout', login.logout);
  app.get('/users', user.list);
  app.get("/blog", blog.get);
  app.get("/blog", blog.get);
  app.get("/demo", demo.get);
  app.get('/upload', file.get);
  app.post('/upload', file.post);
  app.post('/upload/editor', file.validator, file.editor);
  app.get('/mail', mail.get);
  app.post('/mail', mail.post);
  app.get("/xml", xml.get);
  app.get("/test", xml.test);
  app.get("/jadetest", xml.jadetest);
  app.get('/socket', socket.index);
  app.get('/admin', admin.get);
  app.all('/admin/*', admin.auth);
  return app.post('/admin/session', admin.post);
};
