// Generated by CoffeeScript 1.6.1
var Admin, FastLegS, FastLegSBase, config, log, logentries;

logentries = require('node-logentries');

FastLegSBase = require('FastLegS');

FastLegS = new FastLegSBase('mysql');

config = require('../config');

log = logentries.logger(config.logToken);

FastLegS.connect(config.db);

Admin = FastLegS.Base.extend({
  tableName: 'admin',
  primaryKey: 'id'
});

/*
Admin findById
*/


exports.findById = function(id, callback) {
  return Admin.find(id, function(err, results) {
    if (err) {
      console.log(err);
    }
    if (err) {
      log.log("debug", err);
    }
    return callback(results);
  });
};

/*
Admin login
*/


exports.login = function(obj, callback) {
  return Admin.find(obj, function(err, results) {
    if (err) {
      console.log(err);
    }
    if (err) {
      log.log("debug", err);
    }
    return callback(results);
  });
};
