// Generated by CoffeeScript 1.4.0
var Blog, BlogTags, FastLegS, FastLegSBase, config;

FastLegSBase = require('FastLegS');

FastLegS = new FastLegSBase('mysql');

config = require('../config');

FastLegS.connect(config.db);

Blog = FastLegS.Base.extend({
  tableName: 'blog',
  primaryKey: 'id'
});

BlogTags = FastLegS.Base.extend({
  tableName: 'blog_tags',
  primaryKey: 'id'
});

/*
Blog findById
*/


exports.findById = function(id, callback) {
  return Blog.find(id, function(err, results) {
    return callback(err, results);
  });
};
