// Generated by CoffeeScript 1.4.0
var FastLegS, FastLegSBase, User, callback, config;

FastLegSBase = require('FastLegS');

FastLegS = new FastLegSBase('mysql');

config = require('../config');

FastLegS.connect(config.db);

User = FastLegS.Base.extend({
  tableName: 'user',
  primaryKey: 'id'
});

callback = function(err, results) {
  console.dir(err);
  return console.dir(results);
};

exports.all = function() {
  return User.find({}, callback);
};
