// Generated by CoffeeScript 1.4.0
var config, orm;

config = require('../config');

orm = require("orm");

orm.connect(config.db, function(err, db) {
  var Person;
  if (err) {
    throw err;
  }
  Person = db.define("person", {
    name: String,
    surname: String,
    age: Number,
    male: Boolean,
    dt: Date,
    photo: Buffer
  }, {
    methods: {
      fullName: function() {
        return [this.name, this.surname].join(' ');
      }
    }
  });
  Person.hasMany("friends", {
    rate: Number
  });
  return Person.get(1, function(err, Jane) {
    return Jane.getFriends().only("name").run(function(err, people) {
      return console.log(err, people);
    });
  });
});
