// Generated by CoffeeScript 1.6.1
var FastLegS, FastLegSBase, User, config, log, logentries;

logentries = require('node-logentries');

FastLegSBase = require('FastLegS');

FastLegS = new FastLegSBase('mysql');

config = require('../config');

log = logentries.logger(config.logToken);

FastLegS.connect(config.db);

User = FastLegS.Base.extend({
  tableName: 'user_info',
  primaryKey: 'id'
});

/*
User findById
*/


exports.findById = function(id, callback) {
  return User.find(id, function(err, results) {
    if (err) {
      console.log(err);
    }
    if (err) {
      log.log("debug", err);
    }
    return callback(results);
  });
};

/*
*/

