// Generated by CoffeeScript 1.4.0
var config, dao, log, logentries;

logentries = require('node-logentries');

config = require('../config');

dao = require('../models/BlogDao');

log = logentries.logger(config.logToken);

exports.get = function(req, res) {
  return dao.findOne({
    id: req.params.id,
    del_status: 0
  }, function(err, blog) {
    return dao.all({
      del_status: 0
    }, {
      only: ['id', 'title'],
      order: ['-id']
    }, function(err, blogs) {
      console.log(err || blogs);
      log.log("debug", err || blogs);
      if (typeof blog === 'undefined' || typeof blogs === 'undefined') {
        return res.render('error/404');
      } else {
        return res.render('blog', {
          title: 'snode',
          blog: blog,
          blogs: blogs
        });
      }
    });
  });
};
