// Generated by CoffeeScript 1.4.0
var listUrl, needle;

needle = require('needle');

listUrl = "http://douban.fm/j/mine/playlist";

exports.list = function(req, res) {
  return needle.get(listUrl, function(error, resp, result) {
    if (!error && resp.statusCode === 200) {
      return res.json(result);
    }
  });
};

exports.music = function(req, res) {
  var url;
  url = req.query.url;
  return needle.get(url, function(error, resp, result) {
    if (!error && resp.statusCode === 200) {
      return res.end(result);
    }
  });
};
