// Generated by CoffeeScript 1.4.0
var config, dao, data2xml, log, logentries;

logentries = require('node-logentries');

data2xml = require('data2xml')();

config = require('../config');

dao = require('../models/BlogDao');

log = logentries.logger(config.logToken);

exports.get = function(req, res) {
  var rss_obj;
  rss_obj = {
    _attr: {
      version: '2.0'
    },
    channel: {
      title: config.rss.title,
      link: config.rss.link,
      language: config.rss.language,
      description: config.rss.description,
      item: []
    }
  };
  return dao.all({
    del_status: 0
  }, {
    only: ['id', 'title', 'content', 'update_time'],
    limit: config.max_items,
    order: ['-id']
  }, function(blogs) {
    var key, rss_content, value;
    for (key in blogs) {
      value = blogs[key];
      rss_obj.channel.item.push({
        title: value.title,
        link: config.rss.link + 'blog/' + value.id,
        guid: config.rss.link + 'blog/' + value.id,
        description: value.content,
        author: config.rss.author,
        pubDate: value.update_time.toUTCString()
      });
    }
    rss_content = data2xml('rss', rss_obj);
    res.contentType('application/xml');
    return res.send(rss_content);
  });
};
