// Generated by CoffeeScript 1.4.0
/*
 加密 工具
 @type {*}
*/

var crypto;

crypto = require('crypto');

exports.md5Hex = function(str) {
  var md5;
  md5 = crypto.createHash('md5');
  md5.update(str, 'utf8');
  return md5.digest('hex');
};

exports.aesEncrypt = function(str, secret) {
  var cipher, enc;
  cipher = crypto.createCipher('aes192', secret);
  enc = cipher.update(str, 'utf8', 'hex');
  enc += cipher.final('hex');
  return enc;
};

exports.aesDecrypt = function(str, secret) {
  var dec, decipher;
  decipher = crypto.createDecipher('aes192', secret);
  dec = decipher.update(str, 'hex', 'utf8');
  dec += decipher.final('utf8');
  return dec;
};
