// Generated by CoffeeScript 1.5.0
/*
 时间对象的格式化#
 扩展 format 方法
*/

Date.prototype.format = function(format) {
  var k, o;
  o = {
    "M+": this.getMonth() + 1,
    "d+": this.getDate(),
    "h+": this.getHours(),
    "m+": this.getMinutes(),
    "s+": this.getSeconds(),
    "q+": Math.floor((this.getMonth() + 3) / 3),
    "S": this.getMilliseconds()
  };
  if (/(y+)/.test(format)) {
    format = format.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
  }
  for (k in o) {
    if (new RegExp("(" + k + ")").test(format)) {
      format = format.replace(RegExp.$1, RegExp.$1.length === 1 ? o[k] : ("00" + o[k]).substr(("" + o[k]).length));
    }
  }
  return format;
};

/*
 时间格式化 当前时间
 yyyy-MM-dd hh:mm:ss
 @return {*}
*/


exports.time = function() {
  return new Date().format("yyyy-MM-dd hh:mm:ss");
};

/*
 时间格式化 传递的时间
 yyyy-MM-dd hh:mm:ss
*/


exports.format = function(date) {
  return date.format("yyyy-MM-dd hh:mm:ss");
};
