// Generated by CoffeeScript 1.4.0
/*
 时间对象的格式化#
 扩展 format 方法
*/

Date.prototype.format = function(format) {
  var k, o, _i, _len;
  o = {
    "M+": this.getMonth() + 1,
    "d+": this.getDate(),
    "h+": this.getHours(),
    "m+": this.getMinutes(),
    "s+": this.getSeconds(),
    "q+": Math.floor((this.getMonth() + 3) / 3),
    "S": this.getMilliseconds()
  };
  if (/(y+)/.test(format)) {
    format = format.replace(RegExp.$1((this.getFullYear() + "").substr(4 - RegExp.$1.length)));
  }
  for (_i = 0, _len = o.length; _i < _len; _i++) {
    k = o[_i];
    if (new RegExp("(" + k + ")").test(format)) {
      format = format.replace(RegExp.$1, RegExp.$1.length === 1 ? o[k] : ("00" + o[k]).substr(("" + o[k]).length));
    }
  }
  return format;
};

/*
 时间格式化
 yyyy-MM-dd hh:mm:ss
 @return {*}
*/


exports.time = function() {
  return new Date().format("yyyy-MM-dd hh:mm:ss");
};
