// Generated by CoffeeScript 1.4.0
var config, dao, log, logentries;

logentries = require('node-logentries');

dao = require('../../models/BlogDao');

config = require('../../config');

log = logentries.logger(config.logToken);

exports.getAdd = function(req, res) {
  return res.render('admin/blog-add', {
    title: 'snode写博'
  });
};

exports.postAdd = function(req, res) {
  var blog;
  blog = req.body.blog;
  console.log(blog);
  log.log("debug", blog);
  return dao.save(blog, function(err, results) {
    log.log("debug", err || results);
    return res.render('admin/blog-add', {
      title: 'snode写博'
    });
  });
};

exports.getEdit = function(req, res) {
  return dao.findOne({
    id: req.params.id
  }, function(err, blog) {
    log.log("debug", err || blog);
    return res.render('admin/blog-edit', {
      title: 'snode博客编辑',
      blog: blog
    });
  });
};

exports.postEdit = function(req, res) {
  var blog;
  blog = req.body.blog;
  console.log(blog);
  log.log("debug", blog);
  return dao.update(blog, function(err, results) {
    return dao.all({}, {
      only: ['id', 'title', 'del_status'],
      order: ['id']
    }, function(err, blogs) {
      log.log("debug", err || blogs);
      return res.render('admin/index', {
        title: 'Snode管理后台',
        blogs: blogs
      });
    });
  });
};
