// Generated by CoffeeScript 1.6.2
var config, db, dbCache, log, logentries;

logentries = require('node-logentries');

dbCache = require('../../dao/cache').dbCache;

db = require('../../dao/db').db;

config = require('../../config');

log = logentries.logger(config.logToken);

exports.getAdd = function(req, res) {
  return res.render('admin/blog-add', {
    title: 'snode写博'
  });
};

exports.postAdd = function(req, res) {
  var blog;

  blog = req.body.blog;
  blog.create_time = new Date();
  blog.update_time = new Date();
  blog.user_id = new Date();
  console.log("Add:\t" + blog.title);
  log.log("debug", "Add:\t" + blog.title);
  return db.insert('blog', blog, function(error, data) {
    dbCache.reload();
    return res.render('admin/blog-add', {
      title: 'snode写博'
    });
  });
};

exports.getEdit = function(req, res) {
  var blog;

  blog = dbCache.get(req.params.id);
  return res.render('admin/blog-edit', {
    title: 'snode博客编辑',
    blog: blog
  });
};

exports.postEdit = function(req, res) {
  var blog;

  blog = req.body.blog;
  blog.update_time = new Date();
  console.log("Updata:\t" + blog.title);
  log.log("debug", "Updata:\t" + blog.title);
  return db.update('blog', blog, {
    id: blog.id
  }, function(error, data) {
    dbCache.reload();
    return res.redirect('admin/index');
  });
};
